"""
  rag.py

  ChromaDB-based document storage and retrieval pipeline.

  Handles two things:
      1. Storage  — after a document is processed, store its text and
                    metadata in ChromaDB as vector embeddings
      2. Retrieval — given a question, find the most relevant stored
                    document before running LayoutLMv3 on it

  This enables multi-document question answering:
      "Which of my invoices mentions Project Apollo?"
      "Find the contract that has a 30-day termination clause."

  Without ChromaDB, you can only query one document at a time.
  With ChromaDB, the app searches across all stored documents and
  returns the most relevant one for LayoutLMv3 to answer from.

Embeddings are generated by sentence-transformers locally —
no API calls, no cost, runs fully offline.
"""
import chromadb
from chromadb.utils import embedding_functions
from pathlib import Path
from datetime import datetime
from src.config import get_settings
settings = get_settings()
# Embedding model — same one used in Project 2 (AI Meeting Assistant)
# all-MiniLM-L6-v2 is fast, lightweight, and produces strong embeddings
# for English document text.
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
COLLECTION_NAME = "documents"
def get_client() -> chromadb.PersistentClient:
    """
    Returns a persistent ChromaDB client.
    PersistentClient writes embeddings to disk so documents survive
    app restarts. The storage path comes from settings (CHROMA_PERSIST_DIR).
    Returns:
        chromadb.PersistentClient connected to the local vector store.
    """
    Path(settings.chroma_persist_dir).mkdir(parents=True, exist_ok=True)
    return chromadb.PersistentClient(path=settings.chroma_persist_dir)
def get_collection(client: chromadb.PersistentClient) -> chromadb.Collection:
    """
    Returns the documents collection, creating it if it doesn't exist.
    Uses sentence-transformers to generate embeddings automatically
    when documents are added. The embedding function is attached to
    the collection so it runs on every add() and query() call.
    Args:
        client: Active ChromaDB client from get_client().

    Returns:
        ChromaDB Collection for storing and querying document embeddings.
    """
    embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name=EMBEDDING_MODEL
    )
    return client.get_or_create_collection(
        name=COLLECTION_NAME,
        embedding_function=embedding_fn,
        metadata={"hnsw:space": "cosine"}
    )

def store_document(
    doc_id: str,
    text: str,
    filename: str,
    page: int = 0,
    extra_metadata: dict = None,
) -> None:
    """
    Stores a processed document's text and metadata in ChromaDB.

    Called after the OCR pipeline extracts text from a document.
    The text is embedded and stored with metadata so it can be
    retrieved later by semantic search.
    Args:
        doc_id: Unique identifier for this document page
                (e.g. "invoice_2024_page_0"). Must be unique across
                all stored documents.
        text: Full OCR-extracted text of the document page.
        filename: Original filename of the uploaded document.
        page: Page number within the document (0-indexed). Default 0.
        extra_metadata: Optional additional metadata dict to store
                        alongside the document (e.g. upload date, tags).
    """
    if not text.strip():
        print(f"Skipping empty document: {doc_id}")
        return
    client = get_client()
    collection = get_collection(client)
    metadata = {
        "filename": filename,
        "page": page,
        "stored_at": datetime.utcnow().isoformat(),
    }
    if extra_metadata:
        metadata.update(extra_metadata)

    # ChromaDB upsert — updates if doc_id exists, inserts if new
    collection.upsert(
        ids=[doc_id],
        documents=[text],
        metadatas=[metadata]
    )
    print(f"Stored document: {doc_id} ({len(text)} chars)")
def search_documents(
    query: str,
    n_results: int = 3,
) -> list[dict]:
    """
    Searches stored documents by semantic similarity to the query.
    Embeds the query using the same sentence-transformer model used
    during storage, then finds the n most similar document chunks
    using cosine similarity in the vector space.
    Args:
        query: Natural language search query or question.
        n_results: Number of most relevant documents to return. Default 3.
    Returns:
        List of dicts, sorted by relevance (most relevant first):
            - doc_id: Document identifier
            - text: Extracted text of the matching document
            - filename: Original filename
            - page: Page number
            - distance: Cosine distance (lower = more similar)
    """
    client = get_client()
    collection = get_collection(client)
    if collection.count() == 0:
        return []
    n_results = min(n_results, collection.count())
    results = collection.query(
        query_texts=[query],
        n_results=n_results,
        include=["documents", "metadatas", "distances"]
    )
    output = []
    for i in range(len(results["ids"][0])):
        output.append({
            "doc_id": results["ids"][0][i],
            "text": results["documents"][0][i],
            "filename": results["metadatas"][0][i].get("filename", ""),
            "page": results["metadatas"][0][i].get("page", 0),
            "distance": round(results["distances"][0][i], 4),
        })
    return output
def list_documents() -> list[dict]:
    """
    Returns metadata for all documents currently stored in ChromaDB.
    Used by the Gradio frontend to show the user which documents
    are available to query.
    Returns:
        List of dicts with filename, page, doc_id, and stored_at
        for every stored document, sorted by filename.
    """
    client = get_client()
    collection = get_collection(client)
    if collection.count() == 0:
        return []

    results = collection.get(include=["metadatas"])
    docs = []
    for i, doc_id in enumerate(results["ids"]):
        meta = results["metadatas"][i]
        docs.append({
            "doc_id": doc_id,
            "filename": meta.get("filename", ""),
            "page": meta.get("page", 0),
            "stored_at": meta.get("stored_at", ""),
        })

    return sorted(docs, key=lambda x: x["filename"])
def delete_document(doc_id: str) -> None:
    """
    Removes a document from ChromaDB by its ID.
    Args:
        doc_id: The document identifier to delete.
    """
    client = get_client()
    collection = get_collection(client)
    collection.delete(ids=[doc_id])
    print(f"Deleted document: {doc_id}")

'''


  What each part does in plain terms:
  
  ┌──────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┐
  │       Part       │                                        What it does                                         │
  ├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┤
  │ get_client       │ Opens (or creates) the local vector database on disk                                        │
  ├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┤
  │ get_collection   │ Gets the documents collection — attaches the embedding model so every add/query auto-embeds │
  ├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┤
  │ store_document   │ Saves a document's text + metadata after OCR — makes it searchable                          │
  ├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┤
  │ search_documents │ Takes a question, finds the most semantically similar stored documents                      │
  ├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┤
  │ list_documents   │ Returns all stored documents — used to show the user their document library                 │
  ├──────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┤
  │ delete_document  │ Removes a document from the store                                                           │
  └──────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┘

  How the multi-doc flow works end to end:

  User uploads Invoice_A, Invoice_B, Contract_C
      → each gets OCR'd and stored in ChromaDB

  User asks: "Which document mentions Project Apollo?"
      → search_documents("Project Apollo") → returns Invoice_B
      → answer_question_from_image(Invoice_B_image, question) → answer

'''